package pl.com.tt.flex.server.domain.activityMonitor;

public enum ActivityEvent {
    //USER ACTIVITY
    USER_CREATED_ERROR,
    USER_UPDATED_ERROR,
    USER_DELETED_ERROR,

    //PRODUCT ACTIVITY
    PRODUCT_CREATED_ERROR,
    PRODUCT_UPDATED_ERROR,
    PRODUCT_DELETED_ERROR,

    //FORECASTED PRICES ACTIVITY
    FORECASTED_PRICES_CREATED_ERROR,
    FORECASTED_PRICES_DELETED_ERROR,

    //FLEX POTENTIAL ACTIVITY
    FP_CREATED_ERROR,
    FP_UPDATED_ERROR,
    FP_DELETED_ERROR,

    //UNIT ACTIVITY
    UNIT_CREATED_ERROR,
    UNIT_UPDATED_ERROR,
    UNIT_DELETED_ERROR,

    //FORECASTED PRICES ACTIVITY
    SELF_SCHEDULED_CREATED_ERROR,
    SELF_SCHEDULED_DELETED_ERROR,

    //FSP ACTIVITY
    FSP_CREATED_ERROR,
    FSP_UPDATED_ERROR,
    FSP_DELETED_ERROR,

    //DICTIONARY
    DER_TYPE_CREATED_ERROR,
    DER_TYPE_UPDATED_ERROR,
    DER_TYPE_DELETED_ERROR,

    SCHEDULING_UNIT_TYPE_CREATED_ERROR,
    SCHEDULING_UNIT_TYPE_UPDATED_ERROR,
    SCHEDULING_UNIT_TYPE_DELETED_ERROR,

    LOCALIZATION_TYPE_CREATED_ERROR,
    LOCALIZATION_TYPE_UPDATED_ERROR,
    LOCALIZATION_TYPE_DELETED_ERROR,

    //SCHEDULING UNIT
    SCHEDULING_UNIT_CREATED_ERROR,
    SCHEDULING_UNIT_UPDATED_ERROR,
    SCHEDULING_UNIT_DELETED_ERROR,

    //SCHEDULING UNIT PROPOSAL
    SCHEDULING_UNIT_PROPOSAL_CREATED_ERROR,
    SCHEDULING_UNIT_PROPOSAL_UPDATED_ERROR,
    SCHEDULING_UNIT_PROPOSAL_DELETED_ERROR,

    //SUBPORTFOLIO
    SUBPORTFOLIO_CREATED_ERROR,
    SUBPORTFOLIO_UPDATED_ERROR,
    SUBPORTFOLIO_DELETED_ERROR,

    AUCTIONS_SERIES_CREATED_ERROR,
    AUCTIONS_SERIES_UPDATED_ERROR,
    AUCTIONS_SERIES_DELETED_ERROR,
    AUCTIONS_DA_OFFER_CREATED_ERROR,
    AUCTIONS_DA_OFFER_UPDATED_ERROR,
    AUCTIONS_DA_OFFER_DELETED_ERROR,

    AUCTIONS_CMVC_CREATED_ERROR,
    AUCTIONS_CMVC_UPDATED_ERROR,
    AUCTIONS_CMVC_DELETED_ERROR,
    AUCTIONS_CMVC_OFFER_CREATED_ERROR,
    AUCTIONS_CMVC_OFFER_UPDATED_ERROR,
    AUCTIONS_CMVC_OFFER_DELETED_ERROR,

    //SERVER_ERROR
    UNEXPECTED_ERROR;
}
