package pl.com.tt.flex.server.domain.email.enumeration;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum EmailType {
    // DER
    UNIT_CREATION(true),
    UNIT_EDITION(true),
    UNIT_CERTIFICATION(true),
    UNIT_CERTIFICATION_LOSS(true),

    // SUBPORTFOLIO
    SUBPORTFOLIO_CREATION(true),
    SUBPORTFOLIO_EDITION(true),

    //  POTENCJAŁ ELASTYCZNOŚCI
    FLEXIBILITY_POTENTIAL_CREATION(true),
    FLEXIBILITY_POTENTIAL_EDITION(true),
    FLEXIBILITY_POTENTIAL_ASSIGNMENT_TO_REGISTER(true),

    // JEDNOSTKA GRAFIKOWA
    SCHEDULING_UNIT_CREATION(true),
    SCHEDULING_UNIT_EDITION(true),
    SCHEDULING_UNIT_STATUS_CHANGE(true),
    SCHEDULING_UNIT_ASSIGNMENT_TO_REGISTER(true),
    SCHEDULING_UNIT_JOINING_PROPOSAL(false),
    SCHEDULING_UNIT_JOINING_INVIATION(false),
    SCHEDULING_UNIT_READY_FOR_TESTS_NOTIFICATION(true),


    // AKTYWACJA JEDNOSTKI
    UNIT_ACTIVATION_REMINDER_DAY_AHEAD(true),
    UNIT_ACTIVATION_REMINDER_CMVC(true),

    // FSP
    FSP_EDITION(true),
    FSP_REGISTRATION_CONFIRMATION(false),
    FSP_USER_ACTIVATION_CONFIRMATION(false),
    NEW_FSP_REGISTRATION_APPLICATION_NOTIFICATION(true),
    FSP_REGISTRATION_APPLICATION_CONFIRAMTION_NOTIFICATION(true),
    FSP_REGISTRATION_CHANGE_NOTIFICATION(true),
    FSP_REGISTRATION_ACCEPTED(true),
    FSP_REGISTRATION_REJECTED(true),
    FSP_REGISTRATION_APPLICATION_WITHDRAWAL(true),

    // KONTO UŻYTKOWNIKA
    USER_ACCOUNT_CREATION(false),
    USER_ACCOUNT_ACTIVATION(false),
    ACCOUNT_PASSWORD_RESET(false),

    // ALGORYTMY
    OFFERS_USED_IN_ALGORITHM_EXPORT(false),
    ALGORITHM_RESULT_EXPORT(false),

    // OCENA OFERT
    OFFER_EXPORT_TSO(false),
    OFFER_EXPORT_DSO(false),
    CAPACITY_OFFER_ACCEPTED(false),

    // PRODUKT
    PRODUCT_CREATION(true),
    PRODUCT_EDITION(true);


    private final boolean optional;

}
