spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
  jackson:
    serialization:
      indent-output: true
  security:
    user:
      name: admin
      password: admin
      roles: USER, ADMIN

server:
  port: 8761
  compression:
    enabled: false

jhipster:
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800

logging:
  path: C:/flexibility-platform/log/flex-registry
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    pl.com.tt.flex.server: DEBUG
# Add your own application properties here, see the ApplicationProperties class
# application:
