package pl.com.tt.flex.server.domain.screen.enumeration;

public enum Screen {
    // ADMIN SCREENS
    ADMIN_USERS,
    ADMIN_REGISTRATION,
    ADMIN_FSP,
    ADMIN_BSP,
    ADMIN_FLEXIBILITY_POTENTIALS,
    ADMIN_PRODUCTS,
    ADMIN_UNITS,
    ADMIN_FLEX_REGISTER,
    ADMIN_FSP_REGISTRATION,
    ADMIN_DER_TYPES,
    ADMIN_SCHEDULING_UNITS,
    ADMIN_PARTNERSHIP, //SchedulingUnitProposal
    ADMIN_SUBPORTFOLIO,
    ADMIN_REGISTER_SCHEDULING_UNITS,
    ADMIN_SCHEDULING_UNIT_TYPE,
    ADMIN_BIDS_EVALUATION,
    ADMIN_LOCALIZATION_TYPE,
    ADMIN_SELF_SCHEDULE,
    ADMIN_FORECASTED_PRICES,
    ADMIN_KPI,
    ADMIN_SETTLEMENT,
    ADMIN_ONENET_USER,
    ADMIN_CONSUME_DATA,
    ADMIN_OFFERED_SERVICES,
    ADMIN_PROVIDE_DATA,


    // USER SCREENS
    USER_FLEXIBILITY_POTENTIALS,
    USER_REGISTER_FLEXIBILITY_POTENTIALS,
    USER_PRODUCTS,
    USER_UNITS,
    USER_SCHEDULING_UNITS,
    USER_PARTNERSHIP, //SchedulingUnitProposal
    USER_SUBPORTFOLIO,
    USER_REGISTER_SCHEDULING_UNITS,
    USER_SCHEDULING_UNIT_TYPE,
    USER_SELF_SCHEDULE,
    USER_SETTLEMENT,
    USER_BSP
}
