export enum FspUserRegistrationStatus {
  NEW = 'NEW',
  CONFIRMED_BY_FSP = 'CONFIRMED_BY_FSP',
  WITHDRAWN_BY_FSP = 'WITHDRAWN_BY_FSP',
  PRE_CONFIRMED_BY_MO = 'PRE_CONFIRMED_BY_MO',
  USER_ACCOUNT_ACTIVATED_BY_FSP = 'USER_ACCOUNT_ACTIVATED_BY_FSP',
  ACCEPTED_BY_MO = 'ACCEPTED_BY_MO',
  REJECTED_BY_MO = 'REJECTED_BY_MO',
}
