export enum Role {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_TRANSMISSION_SYSTEM_OPERATOR = 'ROLE_TRANSMISSION_SYSTEM_OPERATOR',
  ROLE_DISTRIBUTION_SYSTEM_OPERATOR = 'ROLE_DISTRIBUTION_SYSTEM_OPERATOR',
  ROLE_MARKET_OPERATOR = 'ROLE_MARKET_OPERATOR',
  ROLE_FLEX_SERVICE_PROVIDER = 'ROLE_FLEX_SERVICE_PROVIDER',
  ROLE_BALANCING_SERVICE_PROVIDER = 'ROLE_BALANCING_SERVICE_PROVIDER',
  ROLE_FSP_USER_REGISTRATION = 'ROLE_FSP_USER_REGISTRATION',
  ROLE_FLEX_SERVICE_PROVIDER_AGGREGATED = 'ROLE_FLEX_SERVICE_PROVIDER_AGGREGATED',
}
