package pl.com.tt.flex.model.security.permission;

public final class Authority {

    // OneNet Flexibility Platform Administrator - FLEX ADMIN
    public static final String FLEX_ADMIN_LOGIN = "FLEX_ADMIN_LOGIN";
    public static final String FLEX_ADMIN_USER_VIEW = "FLEX_ADMIN_USER_VIEW";
    public static final String FLEX_ADMIN_USER_MANAGE = "FLEX_ADMIN_USER_MANAGE";
    public static final String FLEX_ADMIN_USER_DELETE = "FLEX_ADMIN_USER_DELETE";
    public static final String FLEX_ADMIN_USER_CHANGE_PASSWORD = "FLEX_ADMIN_USER_CHANGE_PASSWORD";

    public static final String FLEX_ADMIN_PRODUCT_VIEW = "FLEX_ADMIN_PRODUCT_VIEW";
    public static final String FLEX_ADMIN_PRODUCT_MANAGE = "FLEX_ADMIN_PRODUCT_MANAGE";
    public static final String FLEX_ADMIN_PRODUCT_DELETE = "FLEX_ADMIN_PRODUCT_DELETE";

    public static final String FLEX_ADMIN_FSP_REGISTRATION_VIEW = "FLEX_ADMIN_FSP_REGISTRATION_VIEW";
    public static final String FLEX_ADMIN_FSP_REGISTRATION_MANAGE = "FLEX_ADMIN_FSP_REGISTRATION_MANAGE";

    public static final String FLEX_ADMIN_FSP_VIEW = "FLEX_ADMIN_FSP_VIEW";
    public static final String FLEX_ADMIN_FSP_MANAGE = "FLEX_ADMIN_FSP_MANAGE";
    public static final String FLEX_ADMIN_FSP_DELETE = "FLEX_ADMIN_FSP_DELETE";

    public static final String FLEX_ADMIN_UNIT_VIEW = "FLEX_ADMIN_UNIT_VIEW";
    public static final String FLEX_ADMIN_UNIT_MANAGE = "FLEX_ADMIN_UNIT_MANAGE";
    public static final String FLEX_ADMIN_UNIT_DELETE = "FLEX_ADMIN_UNIT_DELETE";

    public static final String FLEX_ADMIN_FP_VIEW = "FLEX_ADMIN_FP_VIEW";
    public static final String FLEX_ADMIN_FP_MANAGE = "FLEX_ADMIN_FP_MANAGE";
    public static final String FLEX_ADMIN_FP_DELETE = "FLEX_ADMIN_FP_DELETE";

    public static final String FLEX_ADMIN_VIEW_NOTIFICATION = "FLEX_ADMIN_VIEW_NOTIFICATION";
    public static final String FLEX_ADMIN_VIEW_PRICES = "FLEX_ADMIN_VIEW_PRICES";

    public static final String FLEX_ADMIN_DER_TYPE_VIEW = "FLEX_ADMIN_DER_TYPE_VIEW";
    public static final String FLEX_ADMIN_DER_TYPE_MANAGE = "FLEX_ADMIN_DER_TYPE_MANAGE";
    public static final String FLEX_ADMIN_DER_TYPE_DELETE = "FLEX_ADMIN_DER_TYPE_DELETE";

    public static final String FLEX_ADMIN_SCHEDULING_UNIT_VIEW = "FLEX_ADMIN_SCHEDULING_UNIT_VIEW";
    public static final String FLEX_ADMIN_SCHEDULING_UNIT_MANAGE = "FLEX_ADMIN_SCHEDULING_UNIT_MANAGE";
    public static final String FLEX_ADMIN_SCHEDULING_UNIT_DELETE = "FLEX_ADMIN_SCHEDULING_UNIT_DELETE";

    public static final String FLEX_ADMIN_SCHEDULING_UNIT_TYPE_VIEW = "FLEX_ADMIN_SCHEDULING_UNIT_TYPE_VIEW";
    public static final String FLEX_ADMIN_SCHEDULING_UNIT_TYPE_MANAGE = "FLEX_ADMIN_SCHEDULING_UNIT_TYPE_MANAGE";
    public static final String FLEX_ADMIN_SCHEDULING_UNIT_TYPE_DELETE = "FLEX_ADMIN_SCHEDULING_UNIT_TYPE_DELETE";

    public static final String FLEX_ADMIN_LOCALIZATION_TYPE_VIEW = "FLEX_ADMIN_LOCALIZATION_TYPE_VIEW";
    public static final String FLEX_ADMIN_LOCALIZATION_TYPE_MANAGE = "FLEX_ADMIN_LOCALIZATION_TYPE_MANAGE";
    public static final String FLEX_ADMIN_LOCALIZATION_TYPE_DELETE = "FLEX_ADMIN_LOCALIZATION_TYPE_DELETE";

    public static final String FLEX_ADMIN_SCHEDULING_UNIT_PROPOSAL_CREATE = "FLEX_ADMIN_SCHEDULING_UNIT_PROPOSAL_CREATE";
	 public static final String FLEX_ADMIN_SCHEDULING_UNIT_PROPOSAL_VIEW = "FLEX_ADMIN_SCHEDULING_UNIT_PROPOSAL_VIEW";
	 public static final String FLEX_ADMIN_SCHEDULING_UNIT_PROPOSAL_MANAGE = "FLEX_ADMIN_SCHEDULING_UNIT_PROPOSAL_MANAGE";

    public static final String FLEX_ADMIN_SELF_SCHEDULE_VIEW = "FLEX_ADMIN_SELF_SCHEDULE_VIEW";
    public static final String FLEX_ADMIN_SELF_SCHEDULE_MANAGE = "FLEX_ADMIN_SELF_SCHEDULE_MANAGE";
    public static final String FLEX_ADMIN_SELF_SCHEDULE_DELETE = "FLEX_ADMIN_SELF_SCHEDULE_DELETE";

    public static final String FLEX_ADMIN_SUBPORTFOLIO_VIEW = "FLEX_ADMIN_SUBPORTFOLIO_VIEW";
    public static final String FLEX_ADMIN_SUBPORTFOLIO_MANAGE = "FLEX_ADMIN_SUBPORTFOLIO_MANAGE";
    public static final String FLEX_ADMIN_SUBPORTFOLIO_DELETE = "FLEX_ADMIN_SUBPORTFOLIO_DELETE";

    public static final String FLEX_ADMIN_AUCTIONS_CMVC_VIEW = "FLEX_ADMIN_AUCTIONS_CMVC_VIEW";
    public static final String FLEX_ADMIN_AUCTIONS_CMVC_MANAGE = "FLEX_ADMIN_AUCTIONS_CMVC_MANAGE";
    public static final String FLEX_ADMIN_AUCTIONS_CMVC_DELETE = "FLEX_ADMIN_AUCTIONS_CMVC_DELETE";

    public static final String FLEX_ADMIN_AUCTIONS_SERIES_VIEW = "FLEX_ADMIN_AUCTIONS_SERIES_VIEW";
    public static final String FLEX_ADMIN_AUCTIONS_SERIES_MANAGE = "FLEX_ADMIN_AUCTIONS_SERIES_MANAGE";
    public static final String FLEX_ADMIN_AUCTIONS_SERIES_DELETE = "FLEX_ADMIN_AUCTIONS_SERIES_DELETE";

    public static final String FLEX_ADMIN_AUCTIONS_DAY_AHEAD_VIEW = "FLEX_ADMIN_AUCTIONS_DAY_AHEAD_VIEW";

    public static final String FLEX_ADMIN_AUCTIONS_OFFER_VIEW = "FLEX_ADMIN_AUCTIONS_OFFER_VIEW";
    public static final String FLEX_ADMIN_AUCTIONS_OFFER_MANAGE = "FLEX_ADMIN_AUCTIONS_OFFER_MANAGE";
    public static final String FLEX_ADMIN_AUCTIONS_OFFER_EXPORT = "FLEX_ADMIN_AUCTIONS_OFFER_EXPORT";
    public static final String FLEX_ADMIN_AUCTIONS_OFFER_EXPORT_SETO = "FLEX_ADMIN_AUCTIONS_OFFER_EXPORT_SETO";
    public static final String FLEX_ADMIN_AUCTIONS_OFFER_IMPORT = "FLEX_ADMIN_AUCTIONS_OFFER_IMPORT";
    public static final String FLEX_ADMIN_AUCTIONS_OFFER_IMPORT_SETO = "FLEX_ADMIN_AUCTIONS_OFFER_IMPORT_SETO";
    public static final String FLEX_ADMIN_AUCTIONS_OFFER_IMPORT_CMVC = "FLEX_ADMIN_AUCTIONS_OFFER_IMPORT_CMVC";
    public static final String FLEX_ADMIN_AUCTIONS_OFFER_IMPORT_PBCM_DANO = "FLEX_ADMIN_AUCTIONS_OFFER_IMPORT_PBCM_DANO";

    public static final String FLEX_ADMIN_AUCTIONS_CMVC_OFFER_VIEW = "FLEX_ADMIN_AUCTIONS_CMVC_OFFER_VIEW";
    public static final String FLEX_ADMIN_AUCTIONS_CMVC_OFFER_CREATE = "FLEX_ADMIN_AUCTIONS_CMVC_OFFER_CREATE";
    public static final String FLEX_ADMIN_AUCTIONS_CMVC_OFFER_EDIT = "FLEX_ADMIN_AUCTIONS_CMVC_OFFER_EDIT";
    public static final String FLEX_ADMIN_AUCTIONS_CMVC_OFFER_DELETE = "FLEX_ADMIN_AUCTIONS_CMVC_OFFER_DELETE";

    public static final String FLEX_ADMIN_AUCTIONS_DAY_AHEAD_OFFER_VIEW = "FLEX_ADMIN_AUCTIONS_DAY_AHEAD_OFFER_VIEW";
    public static final String FLEX_ADMIN_AUCTIONS_DAY_AHEAD_OFFER_CREATE = "FLEX_ADMIN_AUCTIONS_DAY_AHEAD_OFFER_CREATE";
    public static final String FLEX_ADMIN_AUCTIONS_DAY_AHEAD_OFFER_EDIT = "FLEX_ADMIN_AUCTIONS_DAY_AHEAD_OFFER_EDIT";
    public static final String FLEX_ADMIN_AUCTIONS_DAY_AHEAD_OFFER_DELETE = "FLEX_ADMIN_AUCTIONS_DAY_AHEAD_OFFER_DELETE";

    public static final String FLEX_ADMIN_FORECASTED_PRICES_VIEW = "FLEX_ADMIN_FORECASTED_PRICES_VIEW";
    public static final String FLEX_ADMIN_FORECASTED_PRICES_MANAGE = "FLEX_ADMIN_FORECASTED_PRICES_MANAGE";
    public static final String FLEX_ADMIN_FORECASTED_PRICES_DELETE = "FLEX_ADMIN_FORECASTED_PRICES_DELETE";

    public static final String FLEX_ADMIN_AGNO_ALGORITHM_START = "FLEX_ADMIN_AGNO_ALGORITHM_START";
    public static final String FLEX_ADMIN_PBCM_ALGORITHM_START = "FLEX_ADMIN_PBCM_ALGORITHM_START";
    public static final String FLEX_ADMIN_DANO_ALGORITHM_START = "FLEX_ADMIN_DANO_ALGORITHM_START";
    public static final String FLEX_ADMIN_ALGORITHM_STOP = "FLEX_ADMIN_ALGORITHM_STOP";
    public static final String FLEX_ADMIN_ALGORITHM_EVALUATIONS = "FLEX_ADMIN_ALGORITHM_EVALUATIONS";
    public static final String FLEX_ADMIN_ALGORITHM_EVALUATION_OFFERS = "FLEX_ADMIN_ALGORITHM_EVALUATION_OFFERS";

    public static final String FLEX_ADMIN_KDM_MODEL_VIEW = "FLEX_ADMIN_KDM_MODEL_VIEW";
    public static final String FLEX_ADMIN_KDM_MODEL_MANAGE = "FLEX_ADMIN_KDM_MODEL_MANAGE";
    public static final String FLEX_ADMIN_KDM_MODEL_DELETE = "FLEX_ADMIN_KDM_MODEL_DELETE";

    public static final String FLEX_ADMIN_ONENET_USER_VIEW = "FLEX_ADMIN_ONENET_USER_VIEW";
    public static final String FLEX_ADMIN_ONENET_USER_MANAGE = "FLEX_ADMIN_ONENET_USER_MANAGE";
    public static final String FLEX_ADMIN_ONENET_USER_DELETE = "FLEX_ADMIN_ONENET_USER_DELETE";

    public static final String FLEX_ADMIN_OFFERED_SERVICES_VIEW = "FLEX_ADMIN_OFFERED_SERVICES_VIEW";

    public static final String FLEX_ADMIN_PROVIDE_DATA_VIEW = "FLEX_ADMIN_PROVIDE_DATA_VIEW";
    public static final String FLEX_ADMIN_PROVIDE_DATA_SEND = "FLEX_ADMIN_PROVIDE_DATA_SEND";

    public static final String FLEX_ADMIN_CONSUME_DATA_VIEW = "FLEX_ADMIN_CONSUME_DATA_VIEW";

    public static final String FLEX_ADMIN_KPI_VIEW = "FLEX_ADMIN_KPI_VIEW";
    public static final String FLEX_ADMIN_KPI_MANAGE = "FLEX_ADMIN_KPI_MANAGE";
    public static final String FLEX_ADMIN_KPI_DELETE = "FLEX_ADMIN_KPI_DELETE";

    public static final String FLEX_ADMIN_SETTLEMENT_VIEW = "FLEX_ADMIN_SETTLEMENT_VIEW";
    public static final String FLEX_ADMIN_SETTLEMENT_MANAGE = "FLEX_ADMIN_SETTLEMENT_MANAGE";

    public static final String FLEX_ADMIN_CHAT_VIEW = "FLEX_ADMIN_CHAT_VIEW";
    public static final String FLEX_ADMIN_CHAT_MANAGE = "FLEX_ADMIN_CHAT_MANAGE";
    public static final String FLEX_ADMIN_CHAT_MESSAGE_CREATE = "FLEX_ADMIN_CHAT_MESSAGE_CREATE";

    // OneNet Flexibility Platform FSP - FLEX USER
    public static final String FLEX_USER_LOGIN = "FLEX_USER_LOGIN";
    public static final String FLEX_USER_VIEW = "FLEX_USER_VIEW";
    public static final String FLEX_USER_USER_MANAGE = "FLEX_USER_USER_MANAGE";
    public static final String FLEX_USER_CHANGE_PASSWORD = "FLEX_USER_CHANGE_PASSWORD";

    public static final String FLEX_USER_PRODUCT_VIEW = "FLEX_USER_PRODUCT_VIEW";
    public static final String FLEX_USER_PRODUCT_MANAGE = "FLEX_USER_PRODUCT_MANAGE";
    public static final String FLEX_USER_PRODUCT_DELETE = "FLEX_USER_PRODUCT_DELETE";

    public static final String FLEX_USER_FSP_REGISTRATION_VIEW = "FLEX_USER_FSP_REGISTRATION_VIEW";
    public static final String FLEX_USER_FSP_REGISTRATION_MANAGE = "FLEX_USER_FSP_REGISTRATION_MANAGE";

    public static final String FLEX_USER_UNIT_VIEW = "FLEX_USER_UNIT_VIEW";
    public static final String FLEX_USER_UNIT_MANAGE = "FLEX_USER_UNIT_MANAGE";
    public static final String FLEX_USER_UNIT_DELETE = "FLEX_USER_UNIT_DELETE";

    public static final String FLEX_USER_FP_VIEW = "FLEX_USER_FP_VIEW";
    public static final String FLEX_USER_FP_MANAGE = "FLEX_USER_FP_MANAGE";
    public static final String FLEX_USER_FP_DELETE = "FLEX_USER_FP_DELETE";

    public static final String FLEX_USER_VIEW_NOTIFICATION = "FLEX_USER_VIEW_NOTIFICATION";

    public static final String FLEX_USER_DER_TYPE_VIEW = "FLEX_USER_DER_TYPE_VIEW";
    public static final String FLEX_USER_DER_TYPE_MANAGE = "FLEX_USER_DER_TYPE_MANAGE";
    public static final String FLEX_USER_DER_TYPE_DELETE = "FLEX_USER_DER_TYPE_DELETE";

    public static final String FLEX_USER_SCHEDULING_UNIT_VIEW = "FLEX_USER_SCHEDULING_UNIT_VIEW";
    public static final String FLEX_USER_SCHEDULING_UNIT_MANAGE = "FLEX_USER_SCHEDULING_UNIT_MANAGE";
    public static final String FLEX_USER_SCHEDULING_UNIT_DELETE = "FLEX_USER_SCHEDULING_UNIT_DELETE";

    public static final String FLEX_USER_SUBPORTFOLIO_VIEW = "FLEX_USER_SUBPORTFOLIO_VIEW";
    public static final String FLEX_USER_SUBPORTFOLIO_MANAGE = "FLEX_USER_SUBPORTFOLIO_MANAGE";
    public static final String FLEX_USER_SUBPORTFOLIO_DELETE = "FLEX_USER_SUBPORTFOLIO_DELETE";

    public static final String FLEX_USER_SCHEDULING_UNIT_PROPOSAL_VIEW = "FLEX_USER_SCHEDULING_UNIT_PROPOSAL_VIEW";
    public static final String FLEX_USER_SCHEDULING_UNIT_PROPOSAL_CREATE = "FLEX_USER_SCHEDULING_UNIT_PROPOSAL_CREATE";
    public static final String FLEX_USER_SCHEDULING_UNIT_PROPOSAL_MANAGE = "FLEX_USER_SCHEDULING_UNIT_PROPOSAL_MANAGE";

    public static final String FLEX_USER_SELF_SCHEDULE_VIEW = "FLEX_USER_SELF_SCHEDULE_VIEW";
    public static final String FLEX_USER_SELF_SCHEDULE_OFFER_VIEW = "FLEX_USER_SELF_SCHEDULE_OFFER_VIEW";
    public static final String FLEX_USER_SELF_SCHEDULE_MANAGE = "FLEX_USER_SELF_SCHEDULE_MANAGE";
    public static final String FLEX_USER_SELF_SCHEDULE_DELETE = "FLEX_USER_SELF_SCHEDULE_DELETE";

    public static final String FLEX_USER_AUCTIONS_VIEW_PRICES = "FLEX_USER_AUCTIONS_VIEW_PRICES";

    public static final String FLEX_USER_AUCTIONS_SERIES_VIEW = "FLEX_USER_AUCTIONS_SERIES_VIEW";

    public static final String FLEX_USER_AUCTIONS_DAY_AHEAD_VIEW = "FLEX_USER_AUCTIONS_DAY_AHEAD_VIEW";

    public static final String FLEX_USER_AUCTIONS_CMVC_VIEW = "FLEX_USER_AUCTIONS_CMVC_VIEW";
    public static final String FLEX_USER_AUCTIONS_CMVC_MANAGE = "FLEX_USER_AUCTIONS_CMVC_MANAGE";
    public static final String FLEX_USER_AUCTIONS_CMVC_DELETE = "FLEX_USER_AUCTIONS_CMVC_DELETE";

    public static final String FLEX_USER_AUCTIONS_CMVC_OFFER_VIEW = "FLEX_USER_AUCTIONS_CMVC_OFFER_VIEW";
    public static final String FLEX_USER_AUCTIONS_CMVC_OFFER_CREATE = "FLEX_USER_AUCTIONS_CMVC_OFFER_CREATE";
    public static final String FLEX_USER_AUCTIONS_CMVC_OFFER_EDIT = "FLEX_USER_AUCTIONS_CMVC_OFFER_EDIT";
    public static final String FLEX_USER_AUCTIONS_CMVC_OFFER_DELETE = "FLEX_USER_AUCTIONS_CMVC_OFFER_DELETE";

    public static final String FLEX_USER_AUCTIONS_DAY_AHEAD_OFFER_VIEW = "FLEX_USER_AUCTIONS_DAY_AHEAD_OFFER_VIEW";
    public static final String FLEX_USER_AUCTIONS_DAY_AHEAD_OFFER_CREATE = "FLEX_USER_AUCTIONS_DAY_AHEAD_OFFER_CREATE";
    public static final String FLEX_USER_AUCTIONS_DAY_AHEAD_OFFER_EDIT = "FLEX_USER_AUCTIONS_DAY_AHEAD_OFFER_EDIT";
    public static final String FLEX_USER_AUCTIONS_DAY_AHEAD_OFFER_DELETE = "FLEX_USER_AUCTIONS_DAY_AHEAD_OFFER_DELETE";

    public static final String FLEX_USER_BSP_VIEW = "FLEX_USER_BSP_VIEW";

    public static final String FLEX_USER_SCHEDULING_UNIT_TYPE_VIEW = "FLEX_USER_SCHEDULING_UNIT_TYPE_VIEW";

    public static final String FLEX_USER_LOCALIZATION_TYPE_VIEW = "FLEX_USER_LOCALIZATION_TYPE_VIEW";

    public static final String FLEX_USER_SETTLEMENT_VIEW = "FLEX_USER_SETTLEMENT_VIEW";

    public static final String FLEX_USER_CHAT_VIEW = "FLEX_USER_CHAT_VIEW";
    public static final String FLEX_USER_CHAT_MANAGE = "FLEX_USER_CHAT_MANAGE";
    public static final String FLEX_USER_CHAT_MESSAGE_CREATE = "FLEX_USER_CHAT_MESSAGE_CREATE";

    // FLEX ADMIN i FLEX USER
    public static final String FLEX_SYS_ADMINISTRATE = "FLEX_SYS_ADMINISTRATE";
    public static final String FLEX_SYS_DICTIONARY_RESOURCE_VIEW = "FLEX_SYS_DICTIONARY_RESOURCE_VIEW";
    public static final String FLEX_SYS_USER_SCREEN_CONFIG = "FLEX_SYS_USER_SCREEN_CONFIG";
    public static final String FLEX_SYS_USER_EMAIL_CONFIG = "FLEX_SYS_USER_SCREEN_CONFIG";
    public static final String FLEX_SYS_ACTIVITY_MONITOR_VIEW = "FLEX_SYS_ACTIVITY_MONITOR_VIEW";
}
