export enum Screen {
  USER_REGISTER_FLEXIBILITY_POTENTIALS = 'USER_REGISTER_FLEXIBILITY_POTENTIALS',
  USER_FLEXIBILITY_POTENTIALS = 'USER_FLEXIBILITY_POTENTIALS',
  USER_SCHEDULING_UNITS = 'USER_SCHEDULING_UNITS',
  USER_REGISTER_SCHEDULING_UNITS = 'USER_REGISTER_SCHEDULING_UNITS',
  USER_SELF_SCHEDULE = 'USER_SELF_SCHEDULE',
  USER_SUBPORTFOLIO = 'USER_SUBPORTFOLIO',
  USER_PARTNERSHIP = 'USER_PARTNERSHIP',
  USER_PRODUCTS = 'USER_PRODUCTS',
  USER_UNITS = 'USER_UNITS',
  USER_BSP = 'USER_BSP',
  USER_SETTLEMENT = 'USER_SETTLEMENT',
}
